#!/bin/bash
./cryptarithme "HUIT + HUIT = SEIZE"
./cryptarithme "UN + UN + NEUF = ONZE"
./cryptarithme "CINQ + CINQ + VINGT = TRENTE"
./cryptarithme "ZERO + NEUF + NEUF + DOUZE = TRENTE"
./cryptarithme "ZERO + ZERO + ZERO + UN + DOUZE = TREIZE"
./cryptarithme "ZERO + ZERO + SEPT + SEPT + SEIZE = TRENTE"
./cryptarithme "ZERO + UN + TROIS + ONZE + QUINZE = TRENTE"
./cryptarithme "ZERO + TROIS + TROIS + TROIS + SEPT = SEIZE"
./cryptarithme "ZERO + TROIS + TROIS + DOUZE + DOUZE = TRENTE"
./cryptarithme "ZERO + QUATRE + QUATRE + ONZE + ONZE = TRENTE"
./cryptarithme "UN + UN + QUATRE + DOUZE + DOUZE = TRENTE"
./cryptarithme "UN + DEUX + DEUX + DEUX + DEUX = NEUF"
./cryptarithme "UN + QUATRE + CINQ + CINQ + QUINZE = TRENTE"
./cryptarithme "TROIS + TROIS + TROIS + CINQ + SEIZE = TRENTE"
./cryptarithme "QUATRE + QUATRE + QUATRE + NEUF + NEUF = TRENTE"
